# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_donor_list_fileobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_list',
            name='donors',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
