# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_donor_list_donors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor_list',
            name='donors',
        ),
    ]
